db:
  image: postgres:9.4
  ports:
    - "5433:5432"
  environment:
    - POSTGRES_PASSWORD=
    - POSTGRES_USER=innkeepertest
oauth:
  image: danpersa/rusty-oauth:latest
  ports:
    - "6767:6767"
team:
  image: danpersa/rusty-team:latest
  ports:
    - "6768:6768"
innkeeper:
  build: .
  volumes:
    - .:/opt/app
  ports:
    - "9080:9080"
  environment:
    - INNKEEPER_ENV=acceptance-test
  links:
    - db
    - oauth
    - team
